version: 2.1
orbs:
  php: circleci/php@1
jobs:
  test-php:
    docker:
      - image: cimg/php:7.3-node
    steps:
      - checkout
      - run:
          name: Install Composer
          command: |
            curl -sS https://getcomposer.org/installer | php
            mv composer.phar /usr/local/bin/composer
      - run:
          name: Install dependencies
          command: composer install --prefer-dist --no-progress --no-suggest
      - run:
          name: Run tests
          command: ./vendor/bin/phpunit
workflows:
  build-and-test:
    jobs:
      - test-php