version: 2.1
orbs:
  php: circleci/php@1
jobs:
  test-php:
    docker:
      - image: cimg/php:8.0-node
    steps:
      - checkout
      - run:
          name: Install Composer dependencies
          command: |
            cd src
            composer install --prefer-dist --no-progress
      - run:
          name: Run tests
          command: php ./src/vendor/phpunit --testdox ./src/tests/Feature

  deploy-to-ec2:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Create ~/.ssh directory
          command: mkdir -p ~/.ssh
      - run:
          name: Install SSH key
          command: echo "$EC2_DEPLOY_KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
      - run:
          name: Set StrictHostKeyChecking
          command: echo "Host 13.231.147.4\n    StrictHostKeyChecking no" >> ~/.ssh/config
      - run:
          name: Deploy to EC2
          command: |
            ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@13.231.147.4 'cd /home/ec2-user/coachtech_furima && git pull'

workflows:
  version: 2
  build-and-test:
    jobs:
      - test-php
      - deploy-to-ec2:
          requires:
            - test-php
          filters:
            branches:
              only: main
