version: 2.1
orbs:
  php: circleci/php@1
jobs:
  test-php:
    docker:
      - image: cimg/php:7.3-node
    steps:
      - checkout
      - run:
          name: Install Composer dependencies
          command: |
            cd src
            composer install --prefer-dist --no-progress
      - run:
          name: Run tests
          command: ./vendor/bin/phpunit
workflows:
  build-and-test:
    jobs:
      - test-php